### ISSUE TITLE
Why the underscores?

### ISSUE THREAD

**Issue by jjdeprisco** [kd8bxp/Word100#2]
Really appreciate the library. Just getting my feet wet with the LBT, but have done a lot of other projects.

Maybe I am missing something obvious, but why to some entries have underscores and others do not? I tried finding some pattern, but didn't notice one.

**Comment by kd8bxp** [comment]
some "words" are arduino key words - to make them different I put a underscore in front of them.
for example:
begin is a key word - like Serial.begin(9600);  or Wire.begin();
to over come this the library uses _begin for the word "begin"
But that is why some have the underscore and others don't.  
If you can think of another way to do it I would welcome it - I don't really like the underscores either - but it does work and doesn't cause any problems that I am aware of.
There is a list of the words that have the underscores in the Information_README.txt file plus some added abrivations for common words.

**Comment by jjdeprisco** [comment]
Yeah, works great. Only suggestion I have is to add a standard character before *all* of the words so it is something predictable. Then you wouldn't have to guess "do I use an underscore here or not?" You would just always anticipate the special character. Would that work?

**Comment by kd8bxp** [comment]
Not a bad idea really. So all the words would have a underscore in front. I also thought about making them all UPPER case. I'm not sure which I like better.  What would you think of that?

**Comment by kd8bxp** [comment]
@jjdeprisco 
If you don't mind testing the "underscore" branch out I'd be grateful. I have a couple of other projects I need to finish, and just don't have the time to test it right now. 
https://github.com/kd8bxp/Word100/tree/underscore
notes: am is _am, both A.M. and  P.M. (am and pm) have underscores on both sides, to be consistent I did it with pm as well.

**Comment by jjdeprisco** [comment]
Ran test sketch for LBT and it looks good. Made some random changes to check a few words and it seems to be good. Just had to make sure I removed the original library from my setup.

**Comment by kd8bxp** [comment]
@jjdeprisco Thank you - I'm going to clean up the code a little, and make sure the 100+ Word Shield stuff still works - then I'll merge it with the main branch. And close this out.  
It's just going to take me a day or so to finish it.
Thanks for you help.

**Comment by kd8bxp** [comment]
I just finished up a little clean up of the code, and pulled the underscore branch into the master branch.  I didn't really change anything so you should be fine with what you tested.  Thanks again for the help and feedback.
